spring.application.name=barbilling
barbilling.stock.max-refill-quantity=10000
barbilling.stock.max-threshold=1000
barbilling.stock.initial-quantity=50
barbilling.stock.initial-threshold=10
barbilling.default-currency=COP

# Database Configuration
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/barbilling
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update

## Show SQL queries
#spring.jpa.show-sql=true
## Format SQL nicely
#spring.jpa.properties.hibernate.format_sql=true
## Log SQL statements
#logging.level.org.hibernate.SQL=DEBUG
## Log query parameters
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Common Setup for Hibernate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Database admin initialization
app.admin.email=admin@bar.com
app.admin.password=password123

# Initialize database with data-pg.sql AFTER Hibernate creates schema
#spring.jpa.defer-datasource-initialization=false
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:sql/data-pg.sql

# JWT // Must be Base64 string (jwtService -> getSigningKey())
jwt.secret=VGhpc0lzQVNlY3VyZUtleUZvckpXVFRoYXRNZWV0czI1NkJpdHMhIQ==
jwt.expirationSeconds=8640000

# Version Prefix
server.servlet.context-path=/api/v1

